-- smokeping-py 0.1.0 schema for clickhouse
-- generated by: smoke-server schema --driver clickhouse

CREATE DATABASE IF NOT EXISTS smokeping;

CREATE TABLE IF NOT EXISTS smokeping.measurements
(
    ts               DateTime64(3, 'UTC'),
    id               String,
    agent_id         LowCardinality(String),
    agent_location   LowCardinality(String),
    agent_tags       Map(LowCardinality(String), String),
    target_name      LowCardinality(String),
    target_group     LowCardinality(String),
    target           String,
    probe            LowCardinality(String),
    success          UInt8,
    error_type       LowCardinality(String),
    error_message    String,
    latency_ms       Nullable(Float64),
    rtts_ms          Array(Float64),
    rtt_min_ms       Nullable(Float64),
    rtt_avg_ms       Nullable(Float64),
    rtt_median_ms    Nullable(Float64),
    rtt_max_ms       Nullable(Float64),
    rtt_stddev_ms    Nullable(Float64),
    rtt_p95_ms       Nullable(Float64),
    jitter_ms        Nullable(Float64),
    packets_sent     UInt16,
    packets_received UInt16,
    loss_pct         Nullable(Float32),
    resolved_ip      String,
    ip_family        UInt8,
    duration_ms      Nullable(Float64),
    details          String,

    INDEX idx_resolved_ip resolved_ip TYPE bloom_filter(0.01) GRANULARITY 4,
    INDEX idx_target      target      TYPE bloom_filter(0.01) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(ts)
-- Location first: every dashboard filters by vantage point before anything
-- else, and it is the lowest-cardinality useful prefix.
ORDER BY (agent_location, agent_id, probe, target_name, ts)
TTL toDateTime(ts) + INTERVAL 90 DAY
SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS smokeping.mtr_hops
(
    ts             DateTime64(3, 'UTC'),
    measurement_id String,
    agent_id       LowCardinality(String),
    agent_location LowCardinality(String),
    target_name    LowCardinality(String),
    target_group   LowCardinality(String),
    target         String,
    probe          LowCardinality(String),
    hop_no         UInt8,
    hop_host       String,
    hop_ip         String,
    loss_pct       Nullable(Float32),
    sent           Nullable(UInt16),
    received       Nullable(UInt16),
    last_ms        Nullable(Float64),
    avg_ms         Nullable(Float64),
    best_ms        Nullable(Float64),
    worst_ms       Nullable(Float64),
    stddev_ms      Nullable(Float64),
    asn            String,
    is_destination UInt8,
    path_signature String,

    INDEX idx_hop_ip hop_ip TYPE bloom_filter(0.01) GRANULARITY 4
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(ts)
ORDER BY (agent_location, target_name, ts, hop_no)
TTL toDateTime(ts) + INTERVAL 90 DAY
SETTINGS index_granularity = 8192;

CREATE OR REPLACE VIEW smokeping.v_curl AS
SELECT
    ts, agent_id, agent_location, target_name, target_group, target,
    success, error_type, error_message, latency_ms, resolved_ip,
    toUInt16OrZero(JSONExtractString(details, 'http_code'))  AS http_code,
    JSONExtractString(details, 'http_version')               AS http_version,
    JSONExtractString(details, 'url_effective')              AS url_effective,
    JSONExtractString(details, 'content_type')               AS content_type,
    JSONExtractInt(details, 'num_redirects')                 AS num_redirects,
    JSONExtractFloat(details, 'dns_ms')                      AS dns_ms,
    JSONExtractFloat(details, 'tcp_connect_ms')              AS tcp_connect_ms,
    JSONExtractFloat(details, 'tls_handshake_ms')            AS tls_handshake_ms,
    JSONExtractFloat(details, 'request_sent_ms')             AS request_sent_ms,
    JSONExtractFloat(details, 'ttfb_ms')                     AS ttfb_ms,
    JSONExtractFloat(details, 'server_processing_ms')        AS server_processing_ms,
    JSONExtractFloat(details, 'content_transfer_ms')         AS content_transfer_ms,
    JSONExtractFloat(details, 'total_ms')                    AS total_ms,
    JSONExtractInt(details, 'size_download_bytes')           AS size_download_bytes,
    JSONExtractInt(details, 'ssl_verify_result')             AS ssl_verify_result
FROM smokeping.measurements
WHERE probe = 'curl';

CREATE OR REPLACE VIEW smokeping.v_dig AS
SELECT
    ts, agent_id, agent_location, target_name, target_group, target,
    success, error_type, error_message, latency_ms,
    resolved_ip                                              AS dns_server_ip,
    JSONExtractString(details, 'status')                     AS dns_status,
    JSONExtractString(details, 'query_type')                 AS query_type,
    JSONExtractBool(details, 'authoritative')                AS authoritative,
    JSONExtractBool(details, 'recursion_available')          AS recursion_available,
    JSONExtractBool(details, 'truncated')                    AS truncated,
    JSONExtractInt(details, 'answer_count')                  AS answer_count,
    JSONExtractInt(details, 'ttl_min')                       AS ttl_min,
    JSONExtract(details, 'answer_ips', 'Array(String)')      AS answer_ips,
    JSONExtract(details, 'cname_chain', 'Array(String)')     AS cname_chain,
    JSONExtractString(details, 'transport')                  AS transport
FROM smokeping.measurements
WHERE probe = 'dig';

CREATE OR REPLACE VIEW smokeping.v_mtr AS
SELECT
    ts, agent_id, agent_location, target_name, target_group, target,
    success, error_type, latency_ms, resolved_ip              AS destination_ip,
    JSONExtractString(details, 'path_signature')              AS path_signature,
    JSONExtractInt(details, 'hop_count')                      AS hop_count,
    JSONExtractInt(details, 'silent_hops')                    AS silent_hops,
    JSONExtractBool(details, 'path_complete')                 AS path_complete,
    JSONExtractFloat(details, 'destination_loss_pct')         AS destination_loss_pct,
    JSONExtractFloat(details, 'destination_avg_ms')           AS destination_avg_ms,
    JSONExtractFloat(details, 'destination_worst_ms')         AS destination_worst_ms,
    JSONExtract(details, 'path', 'Array(String)')             AS path
FROM smokeping.measurements
WHERE probe = 'mtr';

CREATE OR REPLACE VIEW smokeping.v_ip_performance AS
SELECT
    ts, agent_id, agent_location, probe, target_name, target,
    resolved_ip, ip_family, success, latency_ms, loss_pct,
    rtt_median_ms, rtt_p95_ms, jitter_ms
FROM smokeping.measurements
WHERE resolved_ip != '';

