-- smokeping-py 0.1.0 schema for postgresql
-- generated by: smoke-server schema --driver postgresql

CREATE TABLE IF NOT EXISTS measurements (
    ts               timestamptz      NOT NULL,
    id               text             NOT NULL,
    agent_id         text             NOT NULL,
    agent_location   text             NOT NULL DEFAULT 'unknown',
    agent_tags       jsonb            NOT NULL DEFAULT '{}'::jsonb,
    target_name      text             NOT NULL,
    target_group     text             NOT NULL DEFAULT '/',
    target           text             NOT NULL,
    probe            text             NOT NULL,
    success          boolean          NOT NULL,
    error_type       text             NOT NULL DEFAULT '',
    error_message    text             NOT NULL DEFAULT '',
    latency_ms       double precision,
    rtts_ms          double precision[] NOT NULL DEFAULT '{}',
    rtt_min_ms       double precision,
    rtt_avg_ms       double precision,
    rtt_median_ms    double precision,
    rtt_max_ms       double precision,
    rtt_stddev_ms    double precision,
    rtt_p95_ms       double precision,
    jitter_ms        double precision,
    packets_sent     integer          NOT NULL DEFAULT 0,
    packets_received integer          NOT NULL DEFAULT 0,
    loss_pct         real,
    resolved_ip      text             NOT NULL DEFAULT '',
    ip_family        smallint         NOT NULL DEFAULT 0,
    duration_ms      double precision,
    details          jsonb            NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (ts, id)
);

CREATE TABLE IF NOT EXISTS mtr_hops (
    ts             timestamptz NOT NULL,
    measurement_id text        NOT NULL,
    agent_id       text        NOT NULL,
    agent_location text        NOT NULL DEFAULT 'unknown',
    target_name    text        NOT NULL,
    target_group   text        NOT NULL DEFAULT '/',
    target         text        NOT NULL,
    probe          text        NOT NULL DEFAULT 'mtr',
    hop_no         smallint    NOT NULL,
    hop_host       text        NOT NULL DEFAULT '',
    hop_ip         text        NOT NULL DEFAULT '',
    loss_pct       real,
    sent           integer,
    received       integer,
    last_ms        double precision,
    avg_ms         double precision,
    best_ms        double precision,
    worst_ms       double precision,
    stddev_ms      double precision,
    asn            text        NOT NULL DEFAULT '',
    is_destination boolean     NOT NULL DEFAULT false,
    path_signature text        NOT NULL DEFAULT '',
    PRIMARY KEY (ts, measurement_id, hop_no)
);

CREATE INDEX IF NOT EXISTS measurements_location_probe_target_ts_idx
    ON measurements (agent_location, probe, target_name, ts DESC);

CREATE INDEX IF NOT EXISTS measurements_ts_idx ON measurements (ts DESC);

CREATE INDEX IF NOT EXISTS measurements_resolved_ip_ts_idx
    ON measurements (resolved_ip, ts DESC) WHERE resolved_ip <> '';

CREATE INDEX IF NOT EXISTS measurements_failures_idx
    ON measurements (ts DESC) WHERE success = false;

CREATE INDEX IF NOT EXISTS measurements_details_idx
    ON measurements USING gin (details jsonb_path_ops);

CREATE INDEX IF NOT EXISTS mtr_hops_ip_ts_idx ON mtr_hops (hop_ip, ts DESC);

CREATE INDEX IF NOT EXISTS mtr_hops_target_ts_idx
    ON mtr_hops (agent_location, target_name, ts DESC);

CREATE OR REPLACE VIEW v_curl AS
SELECT
    ts, agent_id, agent_location, target_name, target_group, target,
    success, error_type, error_message, latency_ms, resolved_ip,
    (details->>'http_code')::int              AS http_code,
    details->>'http_version'                  AS http_version,
    details->>'url_effective'                 AS url_effective,
    details->>'content_type'                  AS content_type,
    (details->>'num_redirects')::int          AS num_redirects,
    (details->>'dns_ms')::double precision    AS dns_ms,
    (details->>'tcp_connect_ms')::double precision   AS tcp_connect_ms,
    (details->>'tls_handshake_ms')::double precision AS tls_handshake_ms,
    (details->>'request_sent_ms')::double precision  AS request_sent_ms,
    (details->>'ttfb_ms')::double precision          AS ttfb_ms,
    (details->>'server_processing_ms')::double precision AS server_processing_ms,
    (details->>'content_transfer_ms')::double precision  AS content_transfer_ms,
    (details->>'total_ms')::double precision         AS total_ms,
    (details->>'size_download_bytes')::bigint        AS size_download_bytes,
    (details->>'ssl_verify_result')::int             AS ssl_verify_result
FROM measurements
WHERE probe = 'curl';

CREATE OR REPLACE VIEW v_dig AS
SELECT
    ts, agent_id, agent_location, target_name, target_group, target,
    success, error_type, error_message, latency_ms,
    resolved_ip                               AS dns_server_ip,
    details->>'status'                        AS dns_status,
    details->>'query_type'                    AS query_type,
    (details->>'authoritative')::boolean      AS authoritative,
    (details->>'recursion_available')::boolean AS recursion_available,
    (details->>'truncated')::boolean          AS truncated,
    (details->>'answer_count')::int           AS answer_count,
    (details->>'ttl_min')::int                AS ttl_min,
    details->'answer_ips'                     AS answer_ips,
    details->'cname_chain'                    AS cname_chain,
    details->>'transport'                     AS transport
FROM measurements
WHERE probe = 'dig';

CREATE OR REPLACE VIEW v_mtr AS
SELECT
    ts, agent_id, agent_location, target_name, target_group, target,
    success, error_type, latency_ms,
    resolved_ip                                        AS destination_ip,
    details->>'path_signature'                         AS path_signature,
    (details->>'hop_count')::int                       AS hop_count,
    (details->>'silent_hops')::int                     AS silent_hops,
    (details->>'path_complete')::boolean               AS path_complete,
    (details->>'destination_loss_pct')::double precision AS destination_loss_pct,
    (details->>'destination_avg_ms')::double precision   AS destination_avg_ms,
    (details->>'destination_worst_ms')::double precision AS destination_worst_ms,
    details->'path'                                    AS path
FROM measurements
WHERE probe = 'mtr';

CREATE OR REPLACE VIEW v_ip_performance AS
SELECT
    ts, agent_id, agent_location, probe, target_name, target,
    resolved_ip, ip_family, success, latency_ms, loss_pct,
    rtt_median_ms, rtt_p95_ms, jitter_ms
FROM measurements
WHERE resolved_ip <> '';

CREATE OR REPLACE FUNCTION smokeping_purge(retention_days integer)
RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
    removed bigint;
    cutoff  timestamptz := now() - make_interval(days => retention_days);
BEGIN
    DELETE FROM mtr_hops     WHERE ts < cutoff;
    DELETE FROM measurements WHERE ts < cutoff;
    GET DIAGNOSTICS removed = ROW_COUNT;
    RETURN removed;
END;
$$;

