"""``smoke-server`` command line interface."""

from __future__ import annotations

import argparse
import asyncio
import sys

from smokecommon.configfile import ConfigError
from smokecommon.logging import get_logger, setup_logging
from smokecommon.version import __version__
from smokeserver.auth import generate_key, hash_key
from smokeserver.config import ServerSettings, load_server_config
from smokeserver.storage import StorageError, create_driver

log = get_logger(__name__)

DEFAULT_CONFIG = "/etc/smokeping/server.yaml"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="smoke-server",
        description="Ingest and store measurements from smoke-agents.",
    )
    parser.add_argument("--version", action="version", version=f"smoke-server {__version__}")
    sub = parser.add_subparsers(dest="command")

    def with_config(p: argparse.ArgumentParser) -> argparse.ArgumentParser:
        p.add_argument("-c", "--config", default=DEFAULT_CONFIG, help="path to server.yaml/.toml")
        p.add_argument("--log-level", default=None)
        p.add_argument("--log-format", default=None, choices=["json", "text"])
        return p

    run = with_config(sub.add_parser("run", help="run the HTTP server (default)"))
    run.add_argument("--host", default=None, help="override http.host")
    run.add_argument("--port", type=int, default=None, help="override http.port")
    run.add_argument("--reload", action="store_true", help="uvicorn autoreload (development)")

    with_config(sub.add_parser("check", help="validate the config and exit"))
    with_config(sub.add_parser("migrate", help="create tables and views, then exit"))

    schema = sub.add_parser("schema", help="print the DDL for a driver")
    schema.add_argument(
        "--driver", choices=["clickhouse", "postgresql"], default="clickhouse"
    )
    schema.add_argument("--database", default="smokeping", help="ClickHouse database name")
    schema.add_argument("--retention-days", type=int, default=90)

    genkey = sub.add_parser("genkey", help="generate an API key and its sha256 digest")
    genkey.add_argument("--label", default="agent", help="label to print with the key")

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    command = args.command or "run"

    if command == "genkey":
        return _cmd_genkey(args)
    if command == "schema":
        return _cmd_schema(args)

    try:
        settings = load_server_config(args.config)
    except ConfigError as exc:
        print(f"config error: {exc}", file=sys.stderr)
        return 2

    setup_logging(
        level=args.log_level or settings.logging.level,
        service="smoke-server",
        fmt=args.log_format or settings.logging.format,
    )

    if command == "check":
        return _cmd_check(settings)
    if command == "migrate":
        return asyncio.run(_cmd_migrate(settings))
    return _cmd_run(settings, args)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def _cmd_genkey(args: argparse.Namespace) -> int:
    key = generate_key()
    digest = hash_key(key)
    print("# Give this to the agent (server.api_key):")
    print(key)
    print()
    print("# Put this in the server config -- it never needs the plaintext:")
    print("auth:")
    print("  keys:")
    print(f"    - label: {args.label}")
    print(f"      key_sha256: {digest}")
    print('      agent_ids: ["*"]   # tighten this to specific agent ids')
    return 0


def _cmd_schema(args: argparse.Namespace) -> int:
    """Print DDL straight from the driver, so the SQL files can never drift
    from what the code actually writes."""
    if args.driver == "clickhouse":
        from smokeserver.storage.clickhouse import ClickHouseDriver

        driver = ClickHouseDriver(
            database=args.database, retention_days=args.retention_days
        )
        statements = driver.ddl()
    else:
        from smokeserver.storage.postgres import PostgresDriver

        statements = PostgresDriver(dsn="", retention_days=args.retention_days).ddl()

    print(f"-- smokeping-py {__version__} schema for {args.driver}")
    print("-- generated by: smoke-server schema --driver", args.driver)
    print()
    for statement in statements:
        print(statement.rstrip().rstrip(";") + ";")
        print()
    return 0


def _cmd_check(settings: ServerSettings) -> int:
    try:
        driver = create_driver(settings.storage.driver, settings.storage.options)
    except (StorageError, TypeError) as exc:
        print(f"storage config error: {exc}", file=sys.stderr)
        return 2
    print(f"listen        : {settings.http.host}:{settings.http.port}")
    print(f"storage driver: {driver.name}")
    print(f"api keys      : {len(settings.auth.keys)}")
    print(f"anonymous     : {settings.auth.allow_anonymous}")
    print(f"ensure_schema : {settings.storage.ensure_schema}")
    print("\nconfig OK")
    return 0


async def _cmd_migrate(settings: ServerSettings) -> int:
    driver = create_driver(settings.storage.driver, settings.storage.options)
    try:
        await driver.connect()
        await driver.ensure_schema()
    except StorageError as exc:
        log.error("migration failed", extra={"detail": str(exc)})
        return 1
    finally:
        await driver.close()
    print("schema applied")
    return 0


def _cmd_run(settings: ServerSettings, args: argparse.Namespace) -> int:
    try:
        import uvicorn
    except ImportError:  # pragma: no cover - depends on install extras
        print(
            "uvicorn is required to run the server: pip install 'smokeping-py[server]'",
            file=sys.stderr,
        )
        return 2

    from smokeserver.app import create_app

    host = args.host or settings.http.host
    port = args.port or settings.http.port

    uvicorn.run(
        create_app(settings),
        host=host,
        port=port,
        # Our JSON formatter is already installed on the root logger; letting
        # uvicorn reconfigure logging would replace it with its own format.
        log_config=None,
        access_log=False,
        proxy_headers=settings.http.proxy_headers,
        forwarded_allow_ips="*" if settings.http.proxy_headers else None,
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
